### ISSUE TITLE
docker.io anonymous access failure

### ISSUE THREAD

**Issue by tbortnyk-mi** [buildtool/build-tools#108]
Given I have a dockerfile starting with `FROM golang:1.15 as build`
And no credentials for docker.io
When I build in buildkite with plugin buildtool/buildtools
Then the build should proceed

Actual:
```
[2021-10-28T13:49:00Z]  => ERROR [internal] load metadata for docker.io/library/golang:1.15       0.8s
...
[2021-10-28T13:49:00Z] code: 1, status: failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to fetch oauth token: unexpected status: 401 Unauthorized🚨 Error: The command exited with status 255
--
  | [2021-10-28T13:49:00Z] user command error: The plugin buildtools command hook exited with status 255
```

**Comment by peter-svensson** [comment]
Thanks for reporting.
Most likely it's related to our changes to use Buildkit. As a temporary workaround you can specify the version to 0.2.0 in your setup. 
We will look into it immediately

**Comment by tbortnyk-mi** [comment]
Thank you!

Pinned 0.2.1 works fine

Tim

**Comment by peter-svensson** [comment]
@tbortnyk-mi hmm, I'm having a hard time recreating this problem 😊 
Could you provide some more context about your setup (and does the problem still exists when using v0.2.2?)

**Comment by tbortnyk-mi** [comment]
What we have in buildkite env file:
```
#!/usr/bin/env bash
set -euo pipefail

echo "Exposing BUILDTOOLS_CONTENT"
export DOCKER_API_VERSION=1.40
export BUILDTOOLS_CONTENT=$(cat <<EOF | base64
registry:
  ecr:
    url: *************.dkr.ecr.eu-west-1.amazonaws.com
EOF
)
```
Could docker api version be the cause?

**Comment by peter-svensson** [comment]
> Could docker api version be the cause?

No I don't think that is the problem. I started a new EC2 instance and installed docker on it and then ran the buildkite plugin `command` to fetch the binaries. It works just fine...

```shell
$ docker logout
Removing login credentials for https://index.docker.io/v1/
$  env|grep DOCKER
DOCKER_API_VERSION=1.40
$ BUILDKITE_COMMAND=build ./command 
Waiting for lock
Downloading buildtools version 0.2.2
--2021-10-31 17:22:48--  https://github.com/buildtool/build-tools/releases/download/v0.2.2/build-tools_0.2.2_Linux_x86_64.tar.gz
....
```
Works like a charm..can't really see what could be the issue. Which docker version is installed on your build machines?
```shell
$ docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.40
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by tbortnyk-mi** [comment]
Docker looks a bit outdated indeed
```
buildkite-elastic-agent-i-*************************
aws:ami-id=ami-0da78b8a6b0cdab8d aws:instance-id=i-******************** aws:instance-type=c5.2xlarge buildkite-aws-stack=v5.2.0 docker=19.03.13 queue=default stack=buildkite-elastic-agent
```

**Comment by peter-svensson** [comment]
> Docker looks a bit outdated indeed
> 
> ```
> buildkite-elastic-agent-i-*************************
> aws:ami-id=ami-0da78b8a6b0cdab8d aws:instance-id=i-******************** aws:instance-type=c5.2xlarge buildkite-aws-stack=v5.2.0 docker=19.03.13 queue=default stack=buildkite-elastic-agent
> ```

Yes, I think that is the reason. We have a fix for supporting the older version on the way.

**Comment by peter-svensson** [comment]
@tbortnyk-mi could you please test with the `v0.2.3` release when it has been completed?

**Comment by tbortnyk-mi** [comment]
0.2.3 works fine, thank you Peter!
