### ISSUE TITLE
secrets.sh fails for missing argument on build-tools v0.2.7

### ISSUE THREAD

**Issue by tbortnyk-mi** [buildtool/build-tools#128]
error is present in log: `k8s/secrets.sh: line 5: 1: usage: secrets.sh <environment>`
respective line #5 in script is `ENVIRONMENT="${1?usage: secrets.sh <environment>}"`

**Comment by argoyle** [comment]
Yes, sorry about that. We changed the logic a bit regarding which files and scripts will be applied to a target. You can work around it by renaming the script to `create-secrets.sh` or something else that ends with a non-existing target.

**Comment by argoyle** [comment]
Maybe we should change the logic for scripts again to not have "common" scripts. Leaving this issue open until we have decided.

**Comment by tbortnyk-mi** [comment]
having k8s/\<env-name\>/** would be a cleaner separation from my perspective, albeit some duplication can happen in this case

**Comment by peter-svensson** [comment]
> having k8s/<env-name>/** would be a cleaner separation from my perspective, albeit some duplication can happen in this case

We had that approach at some point in time but we decided against it 😊

**Comment by peter-svensson** [comment]
> Maybe we should change the logic for scripts again to not have "common" scripts. Leaving this issue open until we have decided.

Agreed, we should probably "force" the scripts per environment. I think the odds of them being the same for multiple environments will be slim?
