### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install

### ISSUE THREAD

**Issue by wojtess** [buildtool/build-tools#200]
OS: Win10 21H2
Non admin console
executed in disk C
command: java -jar BuildTools.jar --generate-source --rev 1.18.2 
error:
> [INFO] Reactor Summary:                                                                                                 
[INFO]                                                                                                                  
[INFO] Spigot-API 1.18.2-R0.1-SNAPSHOT .................... FAILURE [ 10.921 s]                                         
[INFO] Spigot-Parent dev-SNAPSHOT ......................... SKIPPED                                                     
[INFO] Spigot 1.18.2-R0.1-SNAPSHOT ........................ SKIPPED                                                     
[INFO] ------------------------------------------------------------------------                                         
[INFO] BUILD FAILURE                                                                                                    
[INFO] ------------------------------------------------------------------------                                         
[INFO] Total time:  11.028 s                                                                                            
[INFO] Finished at: 2022-04-09T23:09:31+02:00                                                                           
[INFO] ------------------------------------------------------------------------                                         
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project spigot-api: Failed to install metadata org.spigotmc:spigot-api/maven-metadata.xml: Could not parse metadata C:\Users\wojtess\.m2\repository\org\spigotmc\spigot-api\maven-metadata-local.xml: only whitespace content allowed before start tag and not \u0 (position: START_DOCUMENT seen \u0... @1:1)  -> [Help 1]                                                       
[ERROR]                                                                                                                 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                     
[ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                  
[ERROR]                                                                                                                 
[ERROR] For more information about the errors and possible solutions, please read the following articles:               
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException                                
Error compiling Spigot. Please check the wiki for FAQs.                                                                 
If this does not resolve your issue then please pastebin the entire BuildTools.log.txt file when seeking support.       java.lang.RuntimeException: Error running command, return status !=0: [C:\WINDOWS\system32\cmd.exe, /D, /C, C:\Program Files\apache-maven-3.6.3/bin/mvn.cmd, -Dbt.name=3475, clean, install]                                                            at org.spigotmc.builder.Builder.runProcess0(Builder.java:973)                                                           at org.spigotmc.builder.Builder.runProcess(Builder.java:904)                                                            at org.spigotmc.builder.Builder.runMaven(Builder.java:873)                                                              at org.spigotmc.builder.Builder.main(Builder.java:709)                                                                  at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:27)

**Comment by peter-svensson** [comment]
Hi

Thanks for the bug report - however I think it might have been posted in the wrong project?

**Comment by wojtess** [comment]
Yes wrong project, sorry for mistake
