### ISSUE TITLE
Support "docker pull" on "FROM" images in Dockerfile

### ISSUE THREAD

**Issue by peter-svensson** [buildtool/build-tools#36]
If I use `latest` (or none) tag in the `FROM` statement remote images is not updated if I have an existing local image.
Would be nice if the default behaviour was to pull the remote image if needed, perhaps being able to disable with a flag `--no-pull` ?

**Comment by argoyle** [comment]
Would be nice even if using a specific version if patch-levels (eg. 3.6.10) also update minor-versions (eg. 3.6) and majors (eg. 3) for example.

**Comment by peter-svensson** [comment]
Sounds nice but probably a harder/more error-prone feature? Perhaps a new issue for that?

**Comment by argoyle** [comment]
I think this change solves the problem with patch-levels etc. as well since it will always try to pull parents, right?
